# Development overrides for docker-compose.yml
# This file is automatically used by docker-compose in development
version: '3.8'

services:
  backend:
    # Development specific settings
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./pmcell.db
      - ENVIRONMENT=development
      - DEBUG=True
      - LOG_LEVEL=DEBUG
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    # Development specific settings
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host

volumes:
  backend_data:
  frontend_node_modules: