version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pmcell-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./pmcell.db
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    networks:
      - pmcell-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pmcell-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    networks:
      - pmcell-network
    depends_on:
      - backend
    command: npm run dev

  # Removido PostgreSQL para usar SQLite e simplificar
  # db:
  #   image: postgres:15-alpine
  #   container_name: pmcell-db
  #   environment:
  #     - POSTGRES_USER=pmcell
  #     - POSTGRES_PASSWORD=pmcell123
  #     - POSTGRES_DB=pmcell
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  backend_data:
  frontend_node_modules:

networks:
  pmcell-network:
    driver: bridge