services:
  - type: web
    name: pmcell-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pmcell-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: SKIP_SECURITY_VALIDATION
        value: true
      - key: ALLOWED_ORIGINS
        value: https://nycolasmancini.github.io
      - key: PYTHONPATH
        value: /opt/render/project/src/backend

databases:
  - name: pmcell-db
    databaseName: pmcell
    user: pmcell
    plan: free