"""fix orderitem separated field name

Revision ID: 24ae2b74d0bc
Revises: de92fe562331
Create Date: 2025-07-12 21:02:50.533952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ae2b74d0bc'
down_revision: Union[str, None] = 'de92fe562331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
