"""Add Order, OrderItem, OrderAccess and PurchaseItem models

Revision ID: 8c317984b1c9
Revises: b5f943afba36
Create Date: 2025-07-12 11:02:00.327309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c317984b1c9'
down_revision: Union[str, None] = 'b5f943afba36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('seller_name', sa.String(length=100), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('logistics_type', sa.String(length=50), nullable=True),
    sa.Column('package_type', sa.String(length=50), nullable=True),
    sa.Column('observations', sa.String(length=500), nullable=True),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.Column('items_separated', sa.Integer(), nullable=False),
    sa.Column('items_in_purchase', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('order_accesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'user_id', 'left_at', name='_order_user_active_uc')
    )
    op.create_index('idx_order_user_active', 'order_accesses', ['order_id', 'user_id', 'left_at'], unique=False)
    op.create_index(op.f('ix_order_accesses_id'), 'order_accesses', ['id'], unique=False)
    op.create_index(op.f('ix_order_accesses_order_id'), 'order_accesses', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_accesses_user_id'), 'order_accesses', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_reference', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('is_separated', sa.Boolean(), nullable=False),
    sa.Column('separated_at', sa.DateTime(), nullable=True),
    sa.Column('separated_by_id', sa.Integer(), nullable=True),
    sa.Column('sent_to_purchase', sa.Boolean(), nullable=False),
    sa.Column('sent_to_purchase_at', sa.DateTime(), nullable=True),
    sa.Column('sent_to_purchase_by_id', sa.Integer(), nullable=True),
    sa.Column('not_sent', sa.Boolean(), nullable=False),
    sa.Column('not_sent_reason', sa.String(length=200), nullable=True),
    sa.Column('not_sent_at', sa.DateTime(), nullable=True),
    sa.Column('not_sent_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['not_sent_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['sent_to_purchase_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['separated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('completion_notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_items_id'), 'purchase_items', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_items_order_item_id'), 'purchase_items', ['order_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_items_order_item_id'), table_name='purchase_items')
    op.drop_index(op.f('ix_purchase_items_id'), table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_order_accesses_user_id'), table_name='order_accesses')
    op.drop_index(op.f('ix_order_accesses_order_id'), table_name='order_accesses')
    op.drop_index(op.f('ix_order_accesses_id'), table_name='order_accesses')
    op.drop_index('idx_order_user_active', table_name='order_accesses')
    op.drop_table('order_accesses')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
