"""add pin_unique field with proper sqlite support

Revision ID: de92fe562331
Revises: e1bd17de2368
Create Date: 2025-07-12 21:01:19.439601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de92fe562331'
down_revision: Union[str, None] = 'e1bd17de2368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin_unique', sa.String(length=4), nullable=False, default='0000'))
    op.create_index(op.f('ix_users_pin_unique'), 'users', ['pin_unique'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_pin_unique'), table_name='users')
    op.drop_column('users', 'pin_unique')
    # ### end Alembic commands ###
