"""update user model with pin_hash and is_active

Revision ID: e1bd17de2368
Revises: 8c317984b1c9
Create Date: 2025-07-12 14:09:28.183103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bd17de2368'
down_revision: Union[str, None] = '8c317984b1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index('ix_users_pin', table_name='users')
    op.drop_column('users', 'pin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin', sa.VARCHAR(length=4), nullable=False))
    op.create_index('ix_users_pin', 'users', ['pin'], unique=1)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'pin_hash')
    # ### end Alembic commands ###
